### ISSUE TITLE
Users not loading

### ISSUE THREAD

**Issue by naps62** [groupbuddies/council#106]
The app is failing to get user data, making us unable to see the authors of each discussion/comment.

I guess this is from one of the latest merges. @gabrielpoca @joaojusto thoughts?

**Comment by gabrielpoca** [comment]
Yes, the request to the backend returns with 500, I'll have a look tomorrow.

**Comment by gabrielpoca** [comment]
@naps62 this issue was 

```
NameError (undefined local variable or method `username' for #<User:0x007fcb0843af50>)
```

I simply run `heroku run rake db:migrate` and it's working now, but I don't understand why heroku didn't run the migration.

**Comment by naps62** [comment]
Oh, I always forget that it doesn't do that automatically.

But yes, it never does. I don't really know why, either
