### ISSUE TITLE
Notifications for new users

### ISSUE THREAD

**Issue by naps62** [groupbuddies/council#118]
I just noticed this when testing my OAuth branch locally

When signing up, I received emails for all previously existing discussions, and they were all marked as having new comments.

The default behaviour should be to set old discussions to `unwatch` so that I wouldn't get either of those (the emails will be especially annoying for new members)

**Comment by gabrielpoca** [comment]
There shouldn't be any notification for new members, I'll have a look to that.

**Comment by bsonntag** [comment]
Fixed in PR https://github.com/groupbuddies/council/pull/156.
