### ISSUE TITLE
last_name mandatory intereferes with Headquarters sign in

### ISSUE THREAD

**Issue by naps62** [groupbuddies/council#119]
Headquarters has a single name filed, while council has a first_name and last_name, both mandatory

So if a HQ user has only a single word, council will try to split it to get both fields.
@joaobborges only had "João" as a name in HQ, which was causing the error

Either we remove the validation and allow empty last_names here, or we force HQ users to have both.
I'm divided between the two options here, with different arguments for each one. suggestions?

**Comment by gabrielpoca** [comment]
Can't we just add an empty string as a default?

**Comment by naps62** [comment]
That's considered blank, so it fails as well

**Comment by bsonntag** [comment]
Fixed in PR https://github.com/groupbuddies/council/pull/157.
