### ISSUE TITLE
Textarea input too small

### ISSUE THREAD

**Issue by joaojusto** [groupbuddies/council#135]
The textarea input on new/edit form should occupy the rest of the page.
Also @johnny1337  said it should have other ux fixes. 

![screen shot 2015-02-26 at 16 50 44](https://cloud.githubusercontent.com/assets/4236592/6396664/a26e8246-bdd7-11e4-8634-a68e28930aa1.png)

**Comment by bsonntag** [comment]
Fixed in https://github.com/groupbuddies/council/pull/163.
