### ISSUE TITLE
Edit comment should be a link instead of a button

### ISSUE THREAD

**Issue by joaojusto** [groupbuddies/council#139]
This:

![screen shot 2015-02-26 at 16 58 29](https://cloud.githubusercontent.com/assets/4236592/6396824/b6ef3700-bdd8-11e4-848d-641b3d37fbd8.png)

Should have this style:

![screen shot 2015-02-26 at 22 08 25](https://cloud.githubusercontent.com/assets/4236592/6403009/157660b6-be04-11e4-887a-b25038874c49.png)

**Comment by gabrielpoca** [comment]
Why should it be a link?

**Comment by joaojusto** [comment]
Because of the style

**Comment by gabrielpoca** [comment]
What do you mean? What's the expected style?

**Comment by joaojusto** [comment]
Sory @gabrielpoca the description was poor. Updated, see it now.
