### ISSUE TITLE
Edit comment should be in place

### ISSUE THREAD

**Issue by joaojusto** [groupbuddies/council#140]
The edit comment action should be in place instead of opening on new comment form.

![screen shot 2015-02-26 at 16 59 46](https://cloud.githubusercontent.com/assets/4236592/6396854/e2cbee22-bdd8-11e4-89c9-c601846cad88.png)

**Comment by gabrielpoca** [comment]
Implemented in https://github.com/groupbuddies/council/commit/d2b9e9139c110b2279b6129585ba25a2d83e1981
