### ISSUE TITLE
The input colors are not correct

### ISSUE THREAD

**Issue by joaojusto** [groupbuddies/council#141]
We have this:

![screen shot 2015-02-26 at 17 01 05](https://cloud.githubusercontent.com/assets/4236592/6396886/1580c428-bdd9-11e4-8767-0edf3f42005c.png)

And we should have this instead: 
![](https://trello-attachments.s3.amazonaws.com/54a139dc577d8c22dd2155a7/320x568/cea95c8570c02d47a75cd5e54ef3ca36/Create_new_discussion_-_step1.png)

**Comment by bsonntag** [comment]
Fixed in PR https://github.com/groupbuddies/council/pull/155.
